#! /bin/sh

crash_report_pipe=/tmp/ss-crash-report-pipe

echo "********* Start SoundSwitch *********"
LD_LIBRARY_PATH=/usr/qt/lib:/usr/SoundSwitch/libraries \
                /usr/SoundSwitch/SoundSwitch -platform offscreen

exitCode=$?
echo "SoundSwitch exit with code ${exitCode}"

[ ${exitCode} -ne 0 ] && {
    echo "crash detected, do report ..."
    echo -n "crash" > ${crash_report_pipe}
}

exit ${exitCode}
