QT.ThreadWeaver.VERSION = 5.26.0
QT.ThreadWeaver.MAJOR_VERSION = 5
QT.ThreadWeaver.MINOR_VERSION = 26
QT.ThreadWeaver.PATCH_VERSION = 0
QT.ThreadWeaver.name = KF5ThreadWeaver
QT.ThreadWeaver.module = KF5ThreadWeaver
QT.ThreadWeaver.defines = 
QT.ThreadWeaver.includes = $$PWD/../../include/KF5/ThreadWeaver
QT.ThreadWeaver.private_includes =
QT.ThreadWeaver.libs = $$PWD/../../lib
QT.ThreadWeaver.depends = core
QT.ThreadWeaver.module_config = 
