#!/bin/sh

VERSION_FILE=/var/tmp/com.denondj.engine.version
NAME=$( sed -rn '\|.*"ProductName": "(.*)".*|s||\1|p' "$VERSION_FILE" )
VERSION=$( sed -rn '\|.*"Version": "(.*)".*|s||\1|p' "$VERSION_FILE" )
COMMIT=$( sed -rn '\|.*"Commit": "(.*)".*|s||\1|p' "$VERSION_FILE" )
FOLDER=${NAME}_-_$VERSION.$COMMIT
VOLUME=$( mount | awk '/\/dev\/sd|mmcblk1/ { print $1; exit }' )

if test -n "$VOLUME"
then
	VOLUME_MOUNT=$( findmnt -no TARGET "$VOLUME" )
	OUTPUT_DIR="$VOLUME_MOUNT/Engine Library/coredumps/$FOLDER"

	# Set flag to inform engine script that a core dump has been written
	# to the user's drive.
	>/tmp/core-dumped-to-user-drive

	mkdir -p "$OUTPUT_DIR"
	printf '%s\n' "$OUTPUT_DIR"
fi
