#!/bin/sh

device=/dev/disk/by-partuuid/931ad49d-ad59-0849-833a-9bf00af5b60e

/sbin/e2label "$device" >/dev/null
ret=$?

if test $ret = 1
then
    mkfs.ext4 -L az01-internal "$device"
    ret=$?
fi

exit $ret
