#!/bin/sh

APPNAME=$1

[ -f /usr/Engine/Scripts/setup-screenrotation.sh ] && source /usr/Engine/Scripts/setup-screenrotation.sh $APPNAME

function cleanup {
	sh /usr/Engine/Scripts/cleanup-$APPNAME.sh
}

while [ 1 ]
do
	rm -f /tmp/engine-quit-reason

	if [ -f /tmp/remote-screen-started ]; then
		echo "Waiting for devices to reappear"
		rm /tmp/remote-screen-started
		sleep 5s
	fi
	/usr/bin/az01-ethernet-speed 100
	/usr/Engine/Engine -d0

	engineExitCode=$?

	# Handle known exit codes:
	if [ "$engineExitCode" -eq 7 ]; then
		echo "Switching mux"
		/bin/az01-usbmux-switch external
		/bin/az01-usbmux-switch internal

	# Report crashes and weird exit codes:
	elif [ "$engineExitCode" -ne 0 ]; then
		if [ "$engineExitCode" -lt 128 ]; then
			echo "Unknown exit code: (${engineExitCode})";
		else
			signum=$(expr $engineExitCode - 128)
			signal=$(kill -l $signum)
			echo "Crash with: $signal"
		fi

		if test -e /tmp/core-dumped-to-user-drive
		then
			rm -f /tmp/core-dumped-to-user-drive
			/usr/Engine/CoredumpReporter $APPNAME --wait
		fi
	fi

	if [ -f /tmp/engine-quit-reason ]; then
		quitReason=$(cat /tmp/engine-quit-reason)
		echo "Engine quit with reason: ${quitReason}"

		case $quitReason in
		"Poweroff")
			echo "Powering off."
			cleanup
			systemctl poweroff
			break
		;;

		"Reboot")
			echo "Rebooting."
			systemctl reboot
			break
		;;

		"UpdateFromLoader")
			echo "Rebooting into update mode."
			cleanup
			reboot loader
			break
		;;

		"UpdateFromFile")
			UPDATE_FILE=$(cat /tmp/update-file-path)
			echo "Starting update from file: $UPDATE_FILE"
			/usr/sbin/az01-update "$UPDATE_FILE"
			break
		;;

		"UpdateFromUrl")
			UPDATE_FILE=$(cat /tmp/update-file-url)
			echo "Starting update from url: $UPDATE_FILE"
			/usr/bin/planck-remote-screen --update "$UPDATE_FILE"
			break
		;;

		"TestApp")
			echo "Starting test app."
			/usr/bin/az01-ethernet-speed 1000
			/bin/${APPNAME}TestApp
			break
		;;

		"ControllerMode")
			echo "Starting controller mode."
			/usr/bin/az01-ethernet-speed 1000
			touch /tmp/remote-screen-started
			/usr/Engine/Scripts/remote-screen.sh $APPNAME
			break
		;;

		"UpdateFirmware")
			/usr/Engine/FirmwareUpdater $APPNAME
			cleanup
			if [ "$APPNAME" = "JC11" ] ; then
				systemctl poweroff
			fi
			break
		;;

		*)
			echo "WARNING: Unknown quit reason \"${quitReason}\""
			break
		;;

		esac

	elif [ "$engineExitCode" -eq 0 ]; then
		echo "Engine exited cleanly without quit reason. Powering off."
		cleanup
		systemctl poweroff
	fi

	echo "***** SOFT RESET *****"
	
	break
done

exit $engineExitCode
