#!/bin/sh

get_pcb_rev() {
	if test -e /sys/firmware/devicetree/base/inmusic,az01-pcb-rev
	then
		printf 'AZ01%s-rev%s\n' \
			"$(cat /sys/firmware/devicetree/base/inmusic,az01-pcb-suffix)" \
			"$(cat /sys/firmware/devicetree/base/inmusic,az01-pcb-rev)"
	elif test -e /sys/firmware/devicetree/base/inmusic,az05-pcb-rev
	then
		printf 'AZ05-rev%s\n' "$(cat /sys/firmware/devicetree/base/inmusic,az05-pcb-rev)"
	else
		echo '<unknown>'
	fi
}

printf '\n# Hardware\n'
printf 'PRODUCT=%s\n' "$(cat /sys/firmware/devicetree/base/inmusic,product-code || echo '<unknown>')"
printf 'PCB_REV=%s\n' "$(get_pcb_rev)"
printf 'SERIAL=%s\n' "$(cat /sys/firmware/devicetree/base/serial-number || echo '<unknown>')"

printf '\n# /etc/az01-release\n'
cat /etc/az01-release

printf '\n# /etc/os-release\n'
cat /etc/os-release

printf '\n# uname -r\nKERNEL_VERSION='
uname -r
